#ifndef PARAMETERS_H
#define PARAMETERSd_H

#define NUMBER_OF_BATHROOMS 10
#define NUMBER_OF_TYPES 2
#define NUMBER_MAX_OF_THREADS_NOT_ALOCATES 100
#define MIN_TIME_TO_SPAW 1
#define MAX_TIME_TO_SPAW 10000 	
#define MIN_TIME_TO_USE_BATHROOM 15000
#define MAX_TIME_TO_USE_BATHROOM 30000
#define PONT_MIN_LINE_PEOPLE 0

#endif