#ifndef PARAMETERS_H
#define PARAMETERSd_H

#define NUMBER_OF_BATHROOMS 10
#define NUMBER_OF_TYPES 2
#define NUMBER_MAX_OF_THREADS_NOT_ALOCATES 100
#define MIN_TIME_TO_SPAW 20
#define MAX_TIME_TO_SPAW 500 	
#define MIN_TIME_TO_USE_BATHROOM 1500
#define MAX_TIME_TO_USE_BATHROOM 3000
#define PONT_MIN_LINE_PEOPLE 0

#endif